volumes:
  mariadb:
  nextcloud_data:
  nextcloud_config:


networks:
  frontend:
  backend:


services:
  init:
    image: busybox
    volumes:
      - .:/var/www/html/custom_apps/files_external_ethswarm
    command: [ "sh", "-c", "chown -R 33:33 /var/www/html" ]

  mariadb:
    image: mariadb:latest
    # set transaction isolation: https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/linux_database_configuration.html
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    restart: always
    networks:
      - backend
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud

  nextcloud:
    build: ./docker/nextcloud
    restart: always
    depends_on:
      - init
      - mariadb
    networks:
      - frontend
      - backend
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - nextcloud_data:/var/www/html/data
      - nextcloud_config:/var/www/html/config
      - ./:/var/www/html/custom_apps/files_external_ethswarm
    ports:
      - "80:80"
      - "443:443"
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
      MYSQL_HOST: mariadb:3306
      NEXTCLOUD_ADMIN_USER: swarmbox
      NEXTCLOUD_ADMIN_PASSWORD: swarmbox

  adminer:
    image: adminer
    restart: always
    networks:
      - frontend
      - backend
    ports:
      - 8082:8080
    links:
      - mariadb
