volumes:
  mariadb:
  nextcloud_app:

networks:
  frontend:
  backend:

services:

  mariadb:
    image: mariadb:latest
    # set transaction isolation: https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/linux_database_configuration.html
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    restart: always
    networks:
      - backend
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  nextcloud:
    build:
      context: ./docker/nextcloud
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - nextcloud_app:/var/www/html
      - ./:/var/www/html/custom_apps/files_external_ethswarm
      - ./dev-environment/nextcloud_source/lib:/var/www/html/lib
      - ./dev-environment/nextcloud_source/apps:/var/www/html/apps
      - ./docker/nextcloud/hooks:/docker-entrypoint-hooks.d
    ports:
      - "80:80"
      - "443:443"
    environment:
      WWWUSER: ${WWWUSER}
      WWWGROUP: ${WWWGROUP}
      APACHE_RUN_USER: ${APACHE_RUN_USER}
      APACHE_RUN_GROUP: ${APACHE_RUN_GROUP}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_HOST: mariadb:3306
      NEXTCLOUD_ADMIN_USER: ${NC_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NC_ADMIN_PASSWORD}
      SWARM_ACCESS_API_TOKEN: ${SWARM_ACCESS_API_TOKEN}

  adminer:
    image: adminer
    restart: always
    networks:
      - frontend
      - backend
    ports:
      - 8082:8080
    links:
      - mariadb
