version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    networks:
      - nextcloud
    environment:
      MYSQL_ROOT_PASSWORD: r00tp@ss
      MYSQL_USER: nextcloud_rw
      MYSQL_PASSWORD: N3xtCl0ud!
      MYSQL_DATABASE: nextcloud
    restart: unless-stopped

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    networks:
      - nextcloud
    ports:
      - "8080:80"
    environment:
      MYSQL_HOST: mariadb
      MYSQL_USER: nextcloud_rw
      MYSQL_PASSWORD: N3xtCl0ud!
      MYSQL_DATABASE: nextcloud
    restart: unless-stopped

  onlyoffice:
    image: onlyoffice/documentserver
    container_name: onlyoffice
    networks:
      - nextcloud
    ports:
      - "8081:80"
    environment:
      JWT_ENABLED: "true"
      JWT_SECRET: "3uL9G3dIJzBcQXErnJX6lHJRfGBd6rMG"
    restart: unless-stopped

networks:
  nextcloud:
    driver: bridge