version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    networks:
      - nextcloud    
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped

  nextcloud:    
    build:
      context: ./docker/nextcloud
      dockerfile: Dockerfile
    container_name: nextcloud
    networks:
      - nextcloud
    ports:
      - "8080:80"
    volumes:
      - nextcloud_app:/var/www/html
      - ./:/var/www/html/custom_apps/files_external_ethswarm
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_HOST: mariadb
    restart: unless-stopped

  onlyoffice:
    image: onlyoffice/documentserver
    container_name: onlyoffice
    networks:
      - nextcloud
    ports:
      - "8081:80"
    environment:
      JWT_ENABLED: "true"
      JWT_SECRET: ${JWT_SECRET}
    restart: unless-stopped

  adminer:
    image: adminer
    restart: always
    networks:
      - nextcloud
    ports:
      - 8082:8080

networks:
  nextcloud:
    driver: bridge

volumes:
  mariadb:
  nextcloud_app: