volumes:
  mariadb:
  nextcloud_data:
  nextcloud_config:

networks:
  frontend:
  backend:

services:

  mariadb:
    image: mariadb:latest
    # set transaction isolation: https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/linux_database_configuration.html
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    restart: always
    networks:
      - backend
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud

  nextcloud:
    build:
      context: ./docker/nextcloud
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - nextcloud_data:/var/www/html/data
      - nextcloud_config:/var/www/html/config
      - ./dev-environment/nextcloud_source:/var/www/html
      - ./:/var/www/html/custom_apps/files_external_ethswarm
      - ./docker/nextcloud/hooks:/docker-entrypoint-hooks.d
    ports:
      - "80:80"
      - "443:443"
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
      MYSQL_HOST: mariadb:3306
      NEXTCLOUD_ADMIN_USER: swarmbox
      NEXTCLOUD_ADMIN_PASSWORD: swarmbox
      SWARM_ACCESS_API_TOKEN: Nz5lDX7PpPGrcdAI5SjPZHVdZJe12AuMOrKfZXaL

  adminer:
    image: adminer
    restart: always
    networks:
      - frontend
      - backend
    ports:
      - 8082:8080
    links:
      - mariadb
